eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://eureka9001.com:9001/eureka/,http://eureka9002.com:9002/eureka/   #依旧用localhost是无法注册的
      #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

server:
  port: 9003
